alter table student
alter
column id add generated by default as identity;
alter table teacher
alter
column id add generated by default as identity;
alter table course
alter
column id add generated by default as identity;
